#!/bin/tcsh
# $Id: comp,v 1.14 2010/07/23 00:48:28 weaver Exp $
#setenv CXXFLAGS -g
#setenv ARCH i386-linux-dbg
setenv CXXFLAGS -O4
setenv ARCH i386-linux-opt
setenv ROOTSYS /reg/g/pcds/package/root


# FRAMEWORK LIBRARY OBJECTS
g++ -m32 $CXXFLAGS -Irelease -Wall `$ROOTSYS/bin/root-config --cflags` -c main.cc
g++ -m32 $CXXFLAGS -Irelease -Wall `$ROOTSYS/bin/root-config --cflags` -c etof.cc
g++ -m32 $CXXFLAGS -Irelease -Wall `$ROOTSYS/bin/root-config --cflags` -c ebeam.cc
g++ -m32 $CXXFLAGS -Irelease -Wall `$ROOTSYS/bin/root-config --cflags` -c rootDump.cc
#--------------------------

#APPLICATION OBJECTS
g++ -m32 $CXXFLAGS -Irelease -Wall `$ROOTSYS/bin/root-config --cflags` -c etof_extra.cc
g++ -m32 $CXXFLAGS -Irelease -Wall `$ROOTSYS/bin/root-config --cflags` -c etof_scan.cc
g++ -m32 $CXXFLAGS -Irelease -Wall `$ROOTSYS/bin/root-config --cflags` -c etof_ptrac.cc
#--------------------------

#APPLICATION LINKING
g++ -m32 $CXXFLAGS rootDump.o etof.o main.o myana.o -Wl,-rpath=$ROOTSYS/lib:./release/build/pdsdata/lib/$ARCH/ `$ROOTSYS/bin/root-config --libs` -Lrelease/build/pdsdata/lib/$ARCH/ -l acqdata -l bld -l xtcdata -l opal1kdata -l camdata -l pnccddata -l controldata -lipimbdata -lprincetondata -levrdata -lencoderdata -o myana
g++ -m32 $CXXFLAGS rootDump.o etof.o ebeam.o main.o etof_extra.o    -Wl,-rpath=$ROOTSYS/lib:./release/build/pdsdata/lib/$ARCH/ `$ROOTSYS/bin/root-config --libs` -Lrelease/build/pdsdata/lib/$ARCH/ -l acqdata -l bld -l xtcdata -l opal1kdata -l camdata -l pnccddata -l controldata -lipimbdata -lprincetondata -levrdata -lencoderdata -o etof_extra
g++ -m32 $CXXFLAGS rootDump.o etof.o ebeam.o main.o etof_scan.o    -Wl,-rpath=$ROOTSYS/lib:./release/build/pdsdata/lib/$ARCH/ `$ROOTSYS/bin/root-config --libs` -Lrelease/build/pdsdata/lib/$ARCH/ -l acqdata -l bld -l xtcdata -l opal1kdata -l camdata -l pnccddata -l controldata -lipimbdata -lprincetondata -levrdata -lencoderdata -o etof_scan
g++ -m32 $CXXFLAGS rootDump.o etof.o ebeam.o main.o etof_ptrac.o    -Wl,-rpath=$ROOTSYS/lib:./release/build/pdsdata/lib/$ARCH/ `$ROOTSYS/bin/root-config --libs` -Lrelease/build/pdsdata/lib/$ARCH/ -l acqdata -l bld -l xtcdata -l opal1kdata -l camdata -l pnccddata -l controldata -lipimbdata -lprincetondata -levrdata -lencoderdata -o etof_ptrac
#--------------------------
